# Generated by Django 6.1 on 2026-09-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('general', 'General user'), ('receiver', 'Receiver'), ('donor', 'Donor'), ('volunteer', 'Volunteer'), ('ngo', 'NGO / community organization'), ('blood_bank', 'Blood bank'), ('admin', 'Administrator')], default='general', max_length=20),
        ),
    ]
